### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by LeCoupa** [mcavage/node-restify#683]
Just to let you know.

![screen shot 2014-09-16 at 11 39 08](https://cloud.githubusercontent.com/assets/1658644/4285314/6ad07380-3d85-11e4-8e31-db19d2e489a7.png)

http://mcavage.me/node-restify/#Routing

**Comment by pfmooney** [comment]
It should be fixed in 22dadff9a21e081fb44f3b0525a9e8b53510f450.
