### ISSUE TITLE
Expose API for handler timers

### ISSUE THREAD

**Issue by DonutEspresso** [mcavage/node-restify#734]
In some cases for dynamic endpoints, I use a handler that resolve a chain of nested handlers. e.g.,

```javascript
server.use(function handler(req, res, next) {
    var async = require('async');
    var handlersToRun = req.handlersArray || [ function A, function B, function C];
    // where A, B, C, are handlers conforming to function(req, res, next) signature
   async.applyEachSeries(handlersToRun, next);
});
```

Applying handlers dynamically means I lose timers for each of the individual handlers, and only get a timer for the wrapping function. I think it would be useful to expose some sort of API that allows developers to manually add timing information that's reported by the auditLogger. I realize it's probably possible to add information directly on to req.timers, but that feels a little intrusive.

**Comment by yunong** [comment]
Implemented.

**Comment by avimar** [comment]
I was wondering about this, saw it on the docs.. but it didn't work.. because you JUST added it, cool. When will it be pushed to NPM?
