### ISSUE TITLE
Fuzzy URL matching

### ISSUE THREAD

**Issue by DonutEspresso** [mcavage/node-restify#735]
Syntactic sugar for fuzzy URL matching would be nice. Restify currently treats `/home` and `/home/` as separate URLs. Perhaps provide a fuzzy flag to treat these as the same URL:

```javascript
server.get({ path: '/home', flags: 'f'}, function handler(req, res, next) {
    ...
));
```

**Comment by yunong** [comment]
@DonutEspresso Please see issue #748

**Comment by DonutEspresso** [comment]
Hurrah! I believe this issue can be closed now.
