### ISSUE TITLE
Route executed even though params are missing

### ISSUE THREAD

**Issue by TheLudd** [mcavage/node-restify#748]
If I have this route:
```
api.get('/user/:id', function(req, res) {
  res.end('You requested user ' + req.params.id);
});
```
... then I would expect the following results for the given requests:
 * ```host/user/1``` -> 200: You requested user 1
 * ```host/user/``` -> 404
 * ```host/user``` -> 404

But this is not what I receive. I get 404 for the last one but 200 for the second one with the body "You requested user"

**Comment by bo01ean** [comment]
You should try a Regex route:
```javascript
api.get(/^\/user\/([0-9]+)$/, function(req, res, next) {
    res.end('You requested user ' + req.params[0]);
    next();
});
```

This should work as expected, and will only match the user route if a numeric id is provided. 404s otherwise

http://mcavage.me/node-restify/#routing

**Comment by TheLudd** [comment]
@bo01ean From your link:

 > restify routing, in 'basic' mode, is pretty much identical to express/sinatra

With express, my case above works according to my expectations. 

I do not consider the regex a viable solution even though it works, the routes become much more cryptic. I consider the current behavior of restify a bug. I wonder if the maintainers agree or disagree.

**Comment by yunong** [comment]
@TheLudd You're route is set explicitly to match /user/:id That's why `/user` or `/user/` fails. Restify does not do fuzzy matching of your routes on simple routes like this. Like @bo01ean states, you should use a regex if you want more expressive pattern matching.

**Comment by TheLudd** [comment]
@yunong  The point was that `/user/` did *not* fail.

To clarify what I wrote in my post
I **do expect** 
 * ```host/user/1``` -> 200: You requested user 1
 * ```host/user/``` -> 404
 * ```host/user``` -> 404

I **actually get**
 * ```host/user/1``` -> 200: You requested user 1
 * ```host/user/``` -> 200: You requested user undefined
 * ```host/user``` -> 404

I consider the middle case to be in error.

My prolblem has arisen because restify is letting unexpected requests through the router.

**Comment by yunong** [comment]
I guess it depends on the definition of the route. '/user/' and '/user' are not the same. In Restify's case, it's parsing the route as '/user/undefined' and running the route handler and giving you 'undefined' as the parameter. As long as this is consistent across the framework, I do not consider this a bug.

**Comment by TheLudd** [comment]
@yunong Agreed very much that `/user/` and `/user` is not the same. What I cannot understand is how `/user/[param]` is considered equal to `/user/`. But if this is the intent and choice of the restify team, so be it.

**Comment by mcavage** [comment]
@TheLudd - actually you just want to add the `sanitizePath` `pre` handler like here: http://mcavage.me/node-restify/#pre

Or rather:

```javascript

api.pre(restify.sanitizePath());

api.get('/user/:id', function(req, res) {
  res.end('You requested user ' + req.params.id);
});
```

This should strip trailing '/', duplicate '//', etc.   The reason this is an explicit step is that in older restify (1.x) this made it *impossible* if somebody wanted non-conforming URLs to be handled differently.  Hope that helps.

**Comment by TheLudd** [comment]
@mcavage That did work. Thank you very much.

Perhaps this is of interest to @DonutEspresso over at #735
