### ISSUE TITLE
minifyify and restify, node version trouble on OSX

### ISSUE THREAD

**Issue by mariusk** [mcavage/node-restify#750]
Minifyify currently does not work with node 0.12. Restify (because of the dtrace-provider dependency) does not seem to work with node 0.10.x on OSX. Any advice?

**Comment by mariusk** [comment]
Seems removing `node_modules/restify/node_modules/dtrace-provider` makes it run again at least (without dtrace).

**Comment by throrin19** [comment]
i've send this issue directly to dtrace : chrisa/node-dtrace-provider#58

**Comment by pfmooney** [comment]
The dtrace-provider module is listed as an optional dependency.
For the widest compatibility with different Node versions, please ensure you're running a current restify release.
