### ISSUE TITLE
switch to v4 UUIDs for [x-]request-id

### ISSUE THREAD

**Issue by trentm** [mcavage/node-restify#758]
/cc @pfmooney @yunong 

Thoughts on switching to v4 uuids by switch to `uuid.v4()` here: https://github.com/mcavage/node-restify/blob/b717db979ab271973f7c915cad71d6db1f1b7eba/lib/request.js#L148 ?

The main motivation is to have UUIDs that are *dissimilar* rather than the time-based v1 UUIDs that end up being hard to distinguish in logs.

As well, my quick test shows that v4 is 3x *faster*, in case that's a concern:

```
> var ben = require('ben');
> var uuid = require('node-uuid')
> ben(10000, function () { uuid.v1() });
0.001
> ben(100000, function () { uuid.v1() });
0.001
> ben(100000, function () { uuid.v1() });
0.00098
> ben(100000, function () { uuid.v4() });
0.00034
> ben(100000, function () { uuid.v4() });
0.0003
> ben(100000, function () { uuid.v4() });
0.0003
```

**Comment by trentm** [comment]
If no objections I'll put this in.

**Comment by yunong** [comment]
Looks good to me. thanks!

**Comment by pfmooney** [comment]
@trentm Good stuff.  Thanks
