### ISSUE TITLE
Support `res.nocache()`

### ISSUE THREAD

**Issue by jwarkentin** [mcavage/node-restify#761]
It would be very handy to have a short hand `res.nocache()` function that does the following:

```js
res.header('Cache-Control', 'no-cache, no-store, must-revalidate'); // HTTP 1.1
res.header('Pragma', 'no-cache'); // HTTP 1.0
res.header('Expires', '0'); // Proxies
```

**Comment by yunong** [comment]
@jwarkentin This is definitely something you can add as part of a simple Restify plugin in the form of a node module. Pull requests are also very welcome!
