### ISSUE TITLE
Chaining handlers & "after" event

### ISSUE THREAD

**Issue by aalimovs** [mcavage/node-restify#766]
Hi,

I'm fully utilising audit logger plugin with the "after" event.

I'm looking to start using chaining handlers inside some routes, where first handler could potentially fire a response to the client without the need to go through the second handler. 

However, firing a response in first handler means second handler will get stuck on its response attempt, therefore, "after" event will not be fired because second handler didn't finish and audit logger will not log this.

    server.get('/test', function(req, res, next) {
        console.log(1);
    	res.json({a:1});
    	return next();
    }, function(req, res, next) {
        console.log(2);
    	res.json({a:2});
        console.log(3);
    	return next();
    });

What is the correct way of doing this?

Should second handler check if response was already fired, therefore just do `return next();`?

Should first handler not fire response and let second handler see what happened in first handler and fire response then?

Something else?

Keen to hear the correct way of handling this! Thanks.

**Comment by DonutEspresso** [comment]
If you've already sent a response out, I believe calling `next(false)` will tell restify to stop processing the request. This will also allow the audit logs to work correctly again.
