### ISSUE TITLE
how to handle server.use() proxy request plugin

### ISSUE THREAD

**Issue by zoharm** [mcavage/node-restify#770]
I made a routing proxy plugin that checks the req.query and decides whether to proxy the request to a remote address or handle it locally.

```javascript
server.use(function (req, res, next) {
    if ('remote' in req.query) {
        routingProxy.proxyRequest(req, res, remoteAddress);
        return;
    } else {
        return next();
    }
});
```

This works, but as you can see, in the case of proxying to a remote address, I am returning from the plugin function WITHOUT calling next(), this is most likely bad practice.

But, if I do call next(), the request gets handled locally (which I don't want) and if I call next with an error, like next(new restify.BadRequestError()) the request still flows down the plugin chain.

How do I correctly stop the request from going through the plugin chain and just stopping at the current plugin? Or is what I'm doing originally actually correct?

Thank you

**Comment by anshou** [comment]
Have you tried calling next(false) before you return in that branch? I believe that should complete the response without any further processing.  If routingProxy.proxyRequest is async, add a callback parameter and call it when you're done in the proxyRequest function; call next() in the function you pass in for the callback.

e.g. routineProxy.proxyRequest(req, res, remoteAddress, function () { next(); });

**Comment by zoharm** [comment]
next(false) seems to work, thank you!
