### ISSUE TITLE
Question of post method performance

### ISSUE THREAD

**Issue by malangstudio** [mcavage/node-restify#786]
Hi guys,

We have one question.

When our server receive many request, sometimes, post method's performance is very poor.

![image](https://cloud.githubusercontent.com/assets/3167459/7003589/093e865e-dc98-11e4-8bba-956c9b2c3b82.png)

How do i debug this?

Regrads.

**Comment by yunong** [comment]
Can you provide code that I can use to reproduce?

On Monday, April 6, 2015, malangstudio <notifications@github.com> wrote:

> Hi guys,
>
> We have one question.
>
> When our server receive many request, sometimes, post method's performance
> is very poor.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/3167459/7003589/093e865e-dc98-11e4-8bba-956c9b2c3b82.png>
>
> How do i debug this?
>
> Regrads.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcavage/node-restify/issues/786>.
>


-- 
Via mobile

**Comment by malangstudio** [comment]
We can't reproduce this phenomenon manually.

But we can reproduce in our production environment. So, we want to know that how do we debug this.

**Comment by yunong** [comment]
What operating system are you on? If you're on Linux or Illumos, could you
please take a core dump of your node.js process in this state and upload it
for me to take a look?

**Comment by malangstudio** [comment]
Hi yunong, we've found problem in other side(not restify).

Thank you for investigating.

Regards,

**Comment by tianp** [comment]
@malangstudio just curious, what do you guys using for the monitoring? Is that an in-house monitoring app?

**Comment by malangstudio** [comment]
@tianp  We are using Newrelic.

**Comment by tianp** [comment]
@malangstudio cool. Thanks a lot!
