### ISSUE TITLE
Possible solution to mandatory calling next()

### ISSUE THREAD

**Issue by kuchumovn** [mcavage/node-restify#797]
What do you think?
Will it solve the issue?

```
web = restify.createServer()

for method in ['get', 'post', 'put', 'delete', 'head']
	do (method) ->
		method_function = web[method]
		web[method] = (path, handler) ->
			simpler_handler = handler
			handler = (request, response, next) ->
				next_explicitly_called = no
				self_detecting_next = ->
					next_explicitly_called = yes
					next.apply(@, arguments)

				simpler_handler(request, response, self_detecting_next)

				if not next_explicitly_called
					self_detecting_next()

			method_function.apply(@, arguments)
```

**Comment by kuchumovn** [comment]
(corrected the code above)

**Comment by yunong** [comment]
Handlers should explicitly invoke next, that's the contract of the handler API. I'm not convinced of any benefits this would add, indeed, this might make user code more error prone.

**Comment by kuchumovn** [comment]
Whatever, just a note for anyone who find this page through Google:

restify call next implicitly explicit automatically

If anyone of the googlers wants to try this code it works, i'm using it in my project
