### ISSUE TITLE
Error in middleware multipart/form-data

### ISSUE THREAD

**Issue by nicolaspeixoto** [mcavage/node-restify#806]
Hi.

I was trying to send a error in next() to a multipart/form-data request, but it stays idle and doesn't send a response to client.

I tried to use server.use and server.pre.

Example:

```javascript
var restify = require('restify');

function filesize(req, res, next){
  if(req.contentType() == "multipart/form-data" && req.contentLength() >= 10000000){ 
    var err = new restify.errors.BadRequestError("");
    return next(err);
  }
  return next();
}
```
Thanks.

**Comment by yunong** [comment]
Can you give me a client example? e.g. a curl command?

**Comment by nicolaspeixoto** [comment]
I find the issue, this isn't a restify error.

You can close the issue.
