### ISSUE TITLE
Error handling based on promises

### ISSUE THREAD

**Issue by nkt** [mcavage/node-restify#814]
Is it possible to handle errors in request handlers using promises?
Bellow is how I'm doing now:
```js
server.get('/users', (req, res, next) => {
  db.getUsers().then((users) => {
    res.send(users);
  }).catch(next);
});
```

Is it possible to do something like this:
```js
server.get('/users', (req, res) => {
  return db.getUsers().then((users) => {
    res.send(users);
  });
});
```

Now I can write wrapper:
```js
function promiseHandler(handler) {
  return (req, res, next) => {
    const result = handler(req, res, next);
    if (result && typeof result.catch === 'function') {
      result.catch(next);
    }
  };
}
```

But how inject this handler right into restify?

**Comment by yunong** [comment]
You have to pass a function to restify that is of the form f(req, res, next). How you decide to implement the internals of the function -- in your case with promises -- is entirely up to you. Currently there are no plans to change the function handler interface in restify.

**Comment by o5** [comment]
I also use the same `.catch(next)` like @nkt but I wanted to be notified (call logger). 

I've created a listener for [`after`](http://restify.com/#event-after) event for this:
```js
server.on('after', (req, res, route, e) => {
    e && Logger.error(e);
});
```

I would like to know, is there any other way to do it?
